name: Auto deploy RPM to QA repository
on: 
  push:
    branches: [ QA ]
    tags: [ 'qa/**' ]
    
jobs:
  Build-RPM:
    runs-on: self-hosted
    env:
      SPEC: experiment.spec
    container:
      image: ghcr.io/fincreg/rockylinux:8-rpmbuild
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Deploy QA
        run: echo "QA packages deployment to qa.yum.domain.tld"