name: Auto deploy RPM to dev repository
on: 
  push:
    branches: [ DEV ]
    tags: [ 'dev/**' ]
    
jobs:
  Build-RPM:
    runs-on: self-hosted
    env:
      SPEC: experiment.spec
    container:
      image: ghcr.io/fincreg/rockylinux:8-rpmbuild
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Deploy DEV
        run: echo "DEV packages deployment to dev.yum.domain.tld"