name: Create RPM building docker image

on:
    push:

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository}}-rpmbuild

jobs:
    docker-build-image:
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v5
              with:
                images: |
                    name/app
                tags: |
                    type=raw,value=${{ github.head_ref }},prefix=verify-

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to GitHub package registry
              uses: docker/login-action@v3
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                context: .
                file: Dockerfile.rockylinux8
                pull: true
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}