name: Create RPM building docker image

on:
    push:

env:
    REGISTRY: ghcr.io

jobs:
    docker-build-image:
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to GitHub package registry
              uses: docker/login-action@v3
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN_WP }}

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                context: .
                file: Dockerfile.rockylinux8
                push: true
                tags: fincreg/rpmbuild-rockylinux-8:latest