name: Deploy production RPM
on: 
  release:
    types: [published]

env:
  SPEC: experiment.spec 
  YUM_REPO: ${{ github.event.release.prerelease && 'stage' || 'live' }}


jobs:
  Deploy-RPM:
    runs-on: self-hosted
    if: match(${{ github.event.release.tag_name }}, '^([0-9]+\\.[0-9]+\\.[0-9]+)(-.+)?$')
    container:
      image: ghcr.io/fincreg/rockylinux:8-rpmbuild
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
        - name: Checkout project
          uses: actions/checkout@v3

        - name: Bump version          
          run: >
                rpmdev-bumpspec 
                -u "${{ github.actor }}"
                -n "${{ github.event.release.tag_name }}" 
                -c "${{ github.event.release.body }}" 
                $GITHUB_WORKSPACE/$SPEC
        
        - name: Cat SPEC
          run: cat $GITHUB_WORKSPACE/$SPEC

        - name: Install dependencies
          run: dnf builddep -y $GITHUB_WORKSPACE/$SPEC --enablerepo powertools

        - name: Build RPM/SRPM packages
          run: >
                rpmbuild -ba
                --define "_topdir $GITHUB_WORKSPACE/rpmbuild"
                --define "_builddir $GITHUB_WORKSPACE"
                $GITHUB_WORKSPACE/$SPEC

        - name: Show built packages
          run: tree $GITHUB_WORKSPACE/rpmbuild/{RPMS/SRPMS}

        - name: Deploy packages
          run: echo "Deploying to $YUM_REPO repository"
