name: Deploy non-production RPM
on: 
  release:
    types: [prereleased]

jobs:
  Deploy-RPM:
    runs-on: self-hosted
    env:
      YUM_REPO: stage
      SPEC: experiment.spec
    container:
      image: ghcr.io/fincreg/rockylinux:8-rpmbuild
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
        - name: Checkout project
          uses: actions/checkout@v3

        - name: Create rpmbuild structure
          run: mkdir -p $GITHUB_WORKSPACE/{SPECS,SOURCES,BUILD,BUILDROOT,RPMS,SRPMS}

        - name: Extract version and release from tag
          run: >
                if [[ ${{ github.event.release.tag_name }} =~ ^([0-9]+\.[0-9]+\.[0-9]+)(-.+)?$ ]]; then
                  VERSION="${BASH_REMATCH[1]}"
                  RELEASE="${BASH_REMATCH[2]:1}"
                  if [ -z "$RELEASE" ]; then RELEASE="1"; fi
                  echo "VERSION=$VERSION" >> $GITHUB_ENV
                  echo "RELEASE=$RELEASE" >> $GITHUB_ENV
                fi

        - name: Bump version
          run: >
                rpmdev-bumpspec 
                -u "${{ github.actor }}"
                -n "${{ env.VERSION }}-${{ env.RELEASE }}" 
                -c "${{ github.event.release.body }}" 
                $GITHUB_WORKSPACE/$SPEC
        
        - name: Show spec
          run: cat $GITHUB_WORKSPACE/$SPEC

        # - name: Install dependencies
        #   run: dnf builddep -y $GITHUB_WORKSPACE/$SPEC --enablerepo powertools

        - name: Build RPM/SRPM packages
          run: >
                rpmbuild -bb
                --define "_topdir $GITHUB_WORKSPACE/rpmbuild"
                --define "_builddir $GITHUB_WORKSPACE"
                $GITHUB_WORKSPACE/$SPEC

        - name: Show build packages
          run: tree $GITHUB_WORKSPACE/rpmbuild/{RPMS/SRPMS}

        - name: Deploy packages
          run: echo "Deploying to $YUM_REPO repository"

        # - name: Upload package artifacts
        #   uses: actions/upload-artifact@v4
        #   with:
        #     path: |
        #       rpmbuild/RPMS/x86_64/**
        #       rpmbuild/SRPMS/**
