
name: Build RPM
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  release:
    types: [published]

jobs:
  Build-And-Push:
    runs-on: self-hosted
    env:
      SPEC: experiment.spec
    container:
      image: ghcr.io/fincreg/rockylinux:8-rpmbuild
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
        - name: Show uri
          run: echo https://api.github.com//repos/$GITHUB_REPOSITORY/releases/$GITHUB_REF_TYPE/$GITHUB_REF_NAME
        - name: Show export
          run: export
        - name: Install jq
          run: dnf install -y jq
        - name: Get Release Notes
          run: |
                curl -s \
                -H "Accept: application/vnd.github.v3+json" \
                -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                https://api.github.com//repos/$GITHUB_REPOSITORY/releases/$GITHUB_REF_TYPE/$GITHUB_REF_NAME | jq -r '.body'
