
name: Build RPM
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  release:
    types: [published]

jobs:
  Build-And-Push:
    runs-on: self-hosted
    env:
      SPEC: experiment.spec
    container:
      image: ghcr.io/fincreg/rockylinux:8-rpmbuild
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
        - name: Print some context
          run: |
                echo ${{ github.event.release }}
                echo ${{ github.event.release.body }}
                echo ${{ github.event.release.tag_name }}
