name: Build RPM
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches: [ master ]
jobs:
  Build:
    runs-on: self-hosted
    env:
      SPEC: experiment.spec
    container:
      image: ghcr.io/fincreg/rockylinux:8-rpmbuild
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Tree before
        run: tree /root $GITHUB_WORKSPACE
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          path: /root/rpmbuild/BUILD/experiment
      - name: Move SPEC
        run: mv /root/rpmbuild/BUILD/experiment/experiment.spec /root/rpmbuild/SPECS/experiment.spec
      - name: Check working directory
        run: pwd
      - name: Check working user
        run: whoami
      # - name: Create structure
      #   run: mkdir -p ~/rpmbuild/{SPECS,SOURCES,BUILD,BUILDROOT,RPMS,SRPMS}
      - name: Install dependencies
        run: dnf builddep -y $SPEC --enablerepo powertools
      # - name: 
      #   run: rpmbuild -ba --define --define $SPEC
      - name: Tree after
        run: tree /root $GITHUB_WORKSPACE


