name: Auto Build RPM
on: 
  push:
    branches: [ master ]
    paths-ignore: [ ".github/workflows/release.yml" ]
    
jobs:
  Build:
    runs-on: self-hosted
    env:
      SPEC: experiment.spec
    container:
      image: ghcr.io/fincreg/rockylinux:8-rpmbuild
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
        - name: Checkout project
          uses: actions/checkout@v3

        - name: Bump version
          run: rpmdev-bumpspec -n "echo $(${{ github.sha }} | cut -c1-7)" $GITHUB_WORKSPACE/$SPEC
        
        - name: Show spec
          run: cat $GITHUB_WORKSPACE/$SPEC

        - name: Install dependencies
          run: dnf builddep -y $GITHUB_WORKSPACE/$SPEC --enablerepo powertools

        - name: Build RPM/SRPM packages
          run: >
                rpmbuild -bb
                --define "_topdir $GITHUB_WORKSPACE/rpmbuild"
                --define "_builddir $GITHUB_WORKSPACE"
                $GITHUB_WORKSPACE/$SPEC

        - name: Show build packages
          run: tree $GITHUB_WORKSPACE/rpmbuild/RPMS