name: Build RPM
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches: [ master ]
jobs:
  Build:
    runs-on: self-hosted
    env:
      SPEC: experiment.spec
    container:
      image: rockylinux:8
    steps:
      - name: Check working directory
        run: pwd
      - name: Check working user
        run: whoami
      # - name: Create structure
      #   run: mkdir -p ~/rpmbuild/{SPECS,SOURCES,BUILD,BUILDROOT,RPMS,SRPMS}
      - name: Install dependencies
        run: dnf builddep -y $GITHUB_WORKSPACE/$SPEC --enablerepo powertools
      # - name: 
      #   run: rpmbuild -ba --define --define $SPEC
      - name: Tree
        run: tree /root $GITHUB_WORKSPACE


