name: Auto Build RPM
on: 
  push:
    branches: [ master ]
    paths-ignore: [ ".github/workflows/release.yml" ]
    
jobs:
  Build-RPM:
    runs-on: self-hosted
    env:
      SPEC: experiment.spec
    container:
      image: ghcr.io/fincreg/rockylinux:8-rpmbuild
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
        - name: Checkout project
          uses: actions/checkout@v3

        - name: Bump version
          run: >
                rpmdev-bumpspec 
                -u "${{ github.event.head_commit.author.name }} <${{ github.event.head_commit.author.email }}>"
                -n "1-${{ github.run_number }}.${{ github.sha }}" 
                -c "${{ github.sha }} : ${{ github.event.head_commit.message }}" 
                $GITHUB_WORKSPACE/$SPEC

        - name: Show spec
          run: cat $GITHUB_WORKSPACE/$SPEC

        - name: Install dependencies
          run: dnf builddep -y $GITHUB_WORKSPACE/$SPEC --enablerepo powertools

        - name: Build RPM/SRPM packages
          run: >
                rpmbuild -bb
                --define "_topdir $GITHUB_WORKSPACE/rpmbuild"
                --define "_builddir $GITHUB_WORKSPACE"
                $GITHUB_WORKSPACE/$SPEC

        - name: Show build packages
          run: tree $GITHUB_WORKSPACE/rpmbuild/RPMS