name: Validate package build

on:
  push:
    branches:
      - '**' # Trigger only on branch pushes (excludes tags)

env:
  SPEC: experiment.spec
  VERSION: "AUTOBUILD"
  RELEASE: "${{ github.run_number }}.${{ github.sha }}"

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        distro: [ 'rockylinux:8', 'rockylinux:9' ]

    steps:
        - name: Checkout project
          uses: actions/checkout@v3

        - name: Setup Docker for RPM build
          run: |
                cat <<EOF > Dockerfile
                FROM ${{ matrix.distro }}
                RUN dnf -y install make rpm-build rpmdevtools dnf-plugins-core tree
                WORKDIR /src
                EOF

        - name: Build RPM/SRPM packages
          run: |
                docker build -t rpmbuild-env .
                docker run --rm \
                  -v ${{ github.workspace }}:/src \
                  rpmbuild-env bash -c "
                    dnf -y builddep ${SPEC} &&
                    rpmbuild -bb ${SPEC} \
                    --define 'version ${VERSION}' \
                    --define 'release ${RELEASE}' \
                    --define '_builddir /src' \
                    --define '_rpmdir /src/RPMS' &&
                    chown -R --reference=Makefile /src/RPMS
                  "

        - name: List built packages
          run: tree ${{ github.workspace }}/RPMS
